// <auto-generated />
using System;
using Hominder.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hominder.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HominderDbContext))]
    partial class HominderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hominder.Domain.Household.HouseholdMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("household_members", (string)null);
                });

            modelBuilder.Entity("Hominder.Domain.Maintenance.MaintenanceTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("maintenance_tasks", (string)null);
                });

            modelBuilder.Entity("Hominder.Domain.Maintenance.MaintenanceTask", b =>
                {
                    b.OwnsMany("Hominder.Domain.Maintenance.Completion", "Completions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CompletedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("CompletedOn")
                                .HasColumnType("date");

                            b1.Property<Guid>("MaintenanceTaskId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("MaintenanceTaskId");

                            b1.ToTable("maintenance_task_completions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceTaskId");
                        });

                    b.Navigation("Completions");
                });
#pragma warning restore 612, 618
        }
    }
}
